server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        dialect: org.hibernate.dialect.H2Dialect
    database-platform:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=true
    username: sa
    password:
#    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

app:
  jwt-secret: foobar
  jwt-expiration-ms: 86400000
